<?php


	$routes_array = [
        "text_img"=>[
            "code"=>"text_img",
            "logo"=>'image',
            "page_title"=>"Text on Image Generator",
            "page_name"=>"برنامج الكلام على الصور",
            "page_desc"=>"يولد نص فوق صورة",
            "page_img"=>"games/text-img.jpg",
            "keywords" => [],
            "breadcrumbs"=>[],
            "link"=> url("games/text-image"),
        ],    
        "memory"=>[
            "code"=>"memory",
            "logo"=>'square-o',
            "page_title"=>"Memory Game",
            "page_name"=>"لعبة الذاكرة",
            "page_desc"=>"أمتحن ذاكرتك مع لعبة الذاكرة",
            "page_img"=>"games/memory.jpg",
            "keywords" => [],
            "breadcrumbs"=>[],
            "link"=> base_url("htmls/games/memory-game.html"),
        ],   
        "chess"=>[
            "code"=>"chess",
            "logo"=>'street-view',
            "page_title"=>"Chess Game",
            "page_name"=>"لعبة الشطرنج",
            "page_desc"=>"ألعب شطرنج ليل نهار اونلين.",
            "page_img"=>"games/chess.jpg",
            "keywords" => [],
            "breadcrumbs"=>[],
            "link"=> url("games/chess"),
        ],                    
        "Maze"=>[
            "code"=>"maze",
            "logo"=>'medium',
            "page_title"=>"Maze",
            "page_name"=>"لعبة المتاهة البسيطة",
            "page_desc"=>"وصل النحلة لبيتها.",
            "page_img"=>"games/bee.jpg",
            "keywords" => [],
            "breadcrumbs"=>[],
            "link"=>url('games/maze1'),
        ],        
        "DrawingApp"=>[
            "code"=>"DrawingApp",
            "logo"=>'pencil-square',
            "page_title"=>"Drawing App",
            "page_name"=>"برنامج الرسام",
            "page_desc"=>"برنامج الرسام لرسم الأشكال المختلفة",
            "page_img"=>"games/drawing.png",
            "keywords" => [],
            "breadcrumbs"=>[],
            "link"=> base_url("htmls/games/drawing-app/drawing-app.html"),
        ], 
        "DrawingApp2"=>[
            "code"=>"DrawingApp2",
            "logo"=>'pencil',
            "page_title"=>"Drawing App 2",
            "page_name"=>"برنامج الرسام 2",
            "page_desc"=>"برنامج الرسام لرسم الأشكال المختلفة",
            "page_img"=>"games/drawing.png",
            "keywords" => [],
            "breadcrumbs"=>[],
            "link"=> base_url("htmls/games/drawing-app-2.html"),
        ], 
        "coloringApp"=>[
            "code"=>"coloringApp",
            "logo"=>'paint-brush',
            "page_title"=>"Coloring App",
            "page_name"=>"برنامج التلوين",
            "page_desc"=>"برنامج يسمح للأطفال بتلوين صورة ما.",
            "page_img"=>"games/duck.png",
            "keywords" => [],
            "breadcrumbs"=>[],
            "link"=> base_url("htmls/games/html5-canvas-drawing-app/html5-canvas-drawing-app.html"),
        ],  
        "coloringApp2"=>[
            "code"=>"coloringApp2",
            "logo"=>'paint-brush',
            "page_title"=>"Coloring App 2",
            "page_name"=>"برنامج التلوين 2",
            "page_desc"=>"برنامج يسمح للأطفال بتلوين صورة ما.",
            "page_img"=>"games/coloring.png",
            "keywords" => [],
            "breadcrumbs"=>[],
            "link"=> base_url("htmls/games/coloring-app-2/coloring-app.html"),
        ],                          
        "dotts_connecting"=>[
            "code"=>"dotts_connecting",
            "logo"=>'dot-circle-o',
            "page_title"=>"Dottes Connection Game",
            "page_name"=>"لعبة توصيل النقاط",
            "page_desc"=>"لعبة توصيل النقاط",
            "page_img"=>"games/dottes.jpg",
            "keywords" => [],
            "breadcrumbs"=>[],
            "link"=> base_url('htmls/games/dott-connecting-app/dott-connecting.html'),
        ],
                       
 	];



