<?php

/*--------------------------------------------------------------
  				Cities & Countries:
--------------------------------------------------------------*/	
$cities = [
	'00'=> [['All Egypt','كل مصر'],[
	]],
	'02'=> [['Alexandria', 'الإسكندرية'],[
['Abu Qir', 'أبو قير'], 
['Agami', 'عجمي'], 
['Al Hadrah', 'الحضرة'], 
['Amreya', 'العامرية'], 
['Asafra', 'العصافرة'], 
['Attarin', 'العطارين'], 
['Awayed', 'العوايد'], 
['Azarita', 'الأزاريطة'], 
['Bacchus', 'باكوس'], 
['Bahray Anfoshy', 'بحرى والأنفوشى'], 
['Bolkly', 'بولكلي'], 
['Borg al Arab', 'برج العرب'], 
['Camp Caesar', 'كامب شيزار'], 
['Cleopatra', 'كليوباترا'], 
['Dekheila', 'الدخيلة'], 
['Dhahria', 'الظاهرية'], 
['El Max', 'المكس'], 
['Fleming', 'فلمنج'], 
['Gianaclis', 'جناكليس'], 
['Glim', 'جليم'], 
['Gomrok', 'الجمرك'], 
['Kabbary', 'القباري'], 
['Kafr Abdo', 'كفر عبدو'], 
['Karmous', 'كرموز'], 
['Koum al Dikka', 'كوم الدكة'], 
['Labban', 'اللبان'], 
['Laurent', 'لوران'], 
['Maamoura', 'المعمورة'], 
['Mandara', 'المندرة'], 
['Manshiyya', 'المنشية'], 
['Miami', 'ميامي'], 
['Mina al Basal', 'مينا البصل'], 
['Moharam Bik', 'محرّم بيك'], 
['Montazah', 'المنتزه'], 
['Nakheel', 'النخيل'], 
['Nozha', 'النزهة'], 
['Raml Station', 'محطة الرمل'], 
['Ras El Tin', 'رأس التين'], 
['Saba Pasha', 'سابا باشا'], 
['Salehia', 'الصالحية'], 
['San Stefano', 'سان ستيفانو'], 
['Schutz', 'شدس'], 
['Seyouf', 'السيوف'], 
['Shatby', 'شاطبي'], 
['Sidi Beshr', 'سيدي بشر'], 
['Sidi Gaber', 'سيدي جابر'], 
['Smoha', 'سموحة'], 
['Sporting', 'سبورتنج'], 
['Stanley', 'ستانلي'], 
['Tosson', 'طوسون'], 
['Victoria', 'فيكتوريا'], 
['Wardian', 'الورديان'], 
['Zezenia', 'زيزينيا'], 
		]],
		'28'=>[['Aswan', 'أسوان'],[
['Abou Simbel', 'ابو سمبل'], 
['Abou al Reish', 'ابو الريش'], 
['Aswan City', 'مدينة أسوان'], 
['Basiliah', 'البصيلية'], 
['Daraw', 'دراو'], 
['Edfu', 'ادفو'], 
['Kalabsha', 'كلابشة'], 
['Kom Ombo', 'كوم امبو'], 
['Nasr al Noba', 'نصر النوبة'], 
['Rdesiah', 'الرديسية'], 
['Sahara', 'صحارى'], 
['Sebaeiah', 'السباعية'], 
		]],
		'25'=>[['Asyut', 'أسيوط'],[
['Abnub', 'أبنوب'], 
['Abu Teeg', 'أبو تيج'], 
['Asyut City', 'مدينة أسيوط'], 
['Badari', 'البدارى'], 
['Dairut', 'ديروط'], 
['Fateh', 'الفتح'], 
['Ghanayem', 'الغنايم'], 
['Manfalut', 'منفلوط'], 
['Qusiya', 'القوصيه'], 
['Sahel Selim', 'ساحل سليم'], 
['Sedfa', 'صدفا'], 
		]],
		'18'=>[['Beheira', 'البحيرة'],[
['Abou Homs', 'أبو حمص'], 
['Abuu al Matamer', 'أبو المطامير'], 
['Badr', 'بدر'], 
['Damanhour', 'دمنهور'], 
['Delengat', 'الدلنجات'], 
['Edko', 'إدكو'], 
['Etay al Barud', 'ايتاي البارود'], 
['Hosh Essa', 'حوش عيسى'], 
['Kafr al Dawwar', 'كفر الدوار'], 
['Kom Hamadah', 'كوم حمادة'], 
['Mahmoudiyah', 'المحمودية'], 
['Nubariyah', 'النوبارية الجديدة'], 
['Rahmaniya', 'الرحمانية'], 
['Rashid', 'رشيد'], 
['Shubrakhit', 'شبراخيت'], 
['Wadi al Natrun', 'وادي النطرون'], 
		]],
		'22'=>[['Beni Suef', 'بني سويف'],[
['Al Feshn', 'الفشن'], 
['Al Wasty', 'الواسطى'], 
['Beba', 'ببا'], 
['Beni Suef City', 'مدينة بني سويف'], 
['Ehnasia', 'إهناسيا'], 
['Nasser', 'ناصر'], 
['New Beni Suef', 'بني سويف الجديدة'], 
['Samasta', 'سمسطا'], 
		]],
		'01'=>[['Cairo', 'القاهرة'],[
['10th Ramadan City', 'العاشر من رمضان'], 
['Abasiya', 'العباسية'], 
['Ain Shams', 'عين شمس'], 
['Ataba', 'العتبة'], 
['Bab al Shereia', 'باب الشعرية'], 
['Basateen', 'البساتين'], 
['Boulaq', 'بولاق'], 
['Cairo', 'القاهرة'], 
['Dar al Salaam', 'دار السلام'], 
['Darb al Ahmar', 'الدرب الأحمر'], 
['Darrasa', 'الدراسة'], 
['Downtown Cairo', 'وسط القاهرة'], 
['Fifth Settlement', 'التجمع الخامس'], 
['Gamaleya', 'الجمالية'], 
['Garden City', 'جاردن سيتي'], 
['Hadayek al Kobba', 'حدائق القبة'], 
['Heliopolis', 'مصر الجديدة'], 
['Helmeya', 'الحلمية'], 
['Helmeya al Gadeda', 'الحلمية الجديدة'], 
['Helwan', 'حلوان'], 
['Katameya', 'القطامية'], 
['Khalifa', 'الخليفة'],  
['Maadi', 'المعادي'], 
['Marg', 'المرج'], 
['Masr al Kadema', 'مصر القديمة'], 
['Matareya', 'المطرية'], 
['Mokattam', 'المقطم'], 
['Moski', 'الموسكي'], 
['Mounira al Gadeda', 'المنيرة الجديدة'], 
['Nasr City', 'مدينة نصر'], 
['New Cairo', 'القاهرة الجديدة'], 
['Nozha', 'النزهة'], 
['Obour City', 'العبور'], 
['Qasr al Nil', 'قصر النيل'], 
['Ramses + Ramses Extension', 'رمسيس و امتداد رمسيس'], 
['Rehab City', 'مدينة الرحاب'], 
['Rod al Farag', 'روض الفرج'], 
['Roda', 'الروضة'], 
['Sahel', 'الساحل'], 
['Salam City', 'مدينة السلام'], 
['Sayeda Zeinab', 'السيدة زينب'], 
['Sharabeya', 'الشرابية'], 
['Shorouk City', 'مدينة الشروق'], 
['Shubra', 'شبرا'], 
['Tebeen', 'التبين'], 
['Tura', 'طرة'], 
['Waili', 'الوايلي'], 
['Zamalek', 'الزمالك'], 
['Zawya al Hamra', 'الزاوية الحمراء'], 
['Zaytoun', 'الزيتون'], 
		]],
		'12'=>[['Dakahlia', 'الدقهلية'],[
['Aga', 'أجا'], 
['Akhtab', 'أخطاب'], 
['Bani Ubayd', 'بني عبيد'], 
['Belqas', 'بلقاس'], 
['Dikirnis', 'دكرنس'], 
['Gamaleya', 'الجمالية'], 
['Gamasa', 'جمصه'], 
['Mansura', 'المنصورة'], 
['Manzala', 'المنزلة'], 
['Matareya', 'المطرية'], 
['Minat al Nasr', 'منية النصر'], 
['Mit Ghamr', 'ميت غمر'], 
['Mit Slseel', 'ميت سلسيل'], 
['Nabaruh', 'نبروه'], 
['Shirbin', 'شربين'], 
['Sinbillawain', 'السنبلاوين'], 
['Talkha', 'طلخا'], 
['Tama al Amdeed', 'تمى الامديد'], 
		]],
		'11'=>[['Damietta', 'دمياط'],[
['Damietta City', 'مدينة دمياط'], 
['Ezbet al Burj', 'عزبة البرج'], 
['Fareskour', 'فارسكور'], 
['Kafr Saad', 'كفر سعد'], 
['Kafr al Bateekh', 'كفر البطيخ'], 
['Mit Abughalb', 'ميت أبوغالب'], 
['New Damietta', 'دمياط الجديدة'], 
['Ras al Bar', 'رأس البر'], 
['Rodah', 'الروضة'], 
['Saro', 'السرو'], 
['Zarqa', 'الزرقا'], 
		]],
		'23'=>[['Fayoum', 'الفيوم'],[
['Atssa', 'أطسا'], 
['Fayoum City', 'مدينة الفيوم'], 
['Ibshway', 'إبشواي'], 
['New Fayoum', 'الفيوم الجديدة'], 
['Sinnuras', 'سنورس'], 
['Tamiya', 'طامية'], 
['Yusuf al Sadiq', 'يوسف الصديق'], 
		]],
		'16'=>[['Gharbia', 'الغربية'],[
['Basyoun', 'بسيون'], 
['Kafr al Zayat', 'كفر الزيات'], 
['Mahalla al Kobra', 'المحلة الكبرى'], 
['Qutour', 'قطور'], 
['Samanoud', 'سمنود'], 
['Santa', 'السنطة'], 
['Tanta', 'طنطا'], 
['Zefta', 'زفتى'], 
		]],
		'21'=>[['Giza', 'الجيزة'],[
['6th of October', '6 أكتوبر'], 
['Abu Rawash', 'أبو رواش'], 
['Agouza', 'العجوزة'], 
['Azizia', 'العزيزية'], 
['Badrasheen', 'البدرشين'], 
['Baragil', 'البراجيل'], 
['Bashtil', 'بشتيل'], 
['Boulaq Dakrour', 'بولاق الدكرور'], 
['Dahab Island and Coldair', 'جزيرة الدهب وكولدير'], 
['Dahshur', 'دهشور'], 
['Dokki', 'الدقى'], 
['Faisal', 'فيصل'], 
['Giza District', 'حى الجيزة'], 
['Hadayek al Ahram', 'حدائق الاهرام'], 
['Haram', 'الهرم'], 
['Haraneya', 'الحرانية'], 
['Hawamdeya', 'الحوامدية'], 
['Imbaba', 'إمبابة'], 
['Kafr Tohormos', 'كفر طهرمس'], 
['Kerdasa', 'كرداسة'], 
['Kit Kat', 'الكيت كات'], 
['Mansuriyya', 'المنصورية'], 
['Markaz al Giza', 'مركز الجيزة'], 
['Mit Oqba', 'ميت عقبة'], 
['Mohandessin', 'المهندسين'], 
['Moneeb', 'المنيب'], 
['Nahia', 'ناهيا'], 
['Omrania', 'العمرانية'], 
['Oseem', 'أوسيم'], 
['Pharaonic Village', 'القرية الفرعونية'], 
['Remaia', 'الرماية'], 
['Saf', 'الصف'], 
['Saft', 'صفط'], 
['Sahafieen', 'الصحفيين'], 
['Sakyet Mekky', 'ساقية مكى'], 
['Saqqara', 'سقارة'], 
['Sheikh Zayed', 'الشيخ زايد'], 
['Souk al Ahad', 'سوق الأحد'], 
['Tersa', 'ترسا'], 
['Warraq', 'الوراق'], 
		]],
		'19'=>[['Ismailia', 'الإسماعيلية'],[
['Abu Swear', 'أبوصوير'], 
['Fayed', 'فايد'], 
['Ismailia City', 'مدينة الإسماعيلية'], 
['Kantara East', 'القنطرة شرق'], 
['Kantara West', 'القنطرة غرب'], 
['Qassaseen', 'القصاصين'], 
['Tal al Kebeer', 'التل الكبير'], 
		]],
		'15'=>[['Kafr al Sheikh', 'كفر الشيخ'],[
['Bella', 'بيلا'], 
['Brolos', 'البرلس'], 
['Desouk', 'دسوق'], 
['Fouh', 'فوه'], 
['Hamoul', 'الحامول'], 
['Kafr al Sheikh City', 'مدينة كفر الشيخ'], 
['Motobas', 'مطوبس'], 
['Qaleen', 'قلين'], 
['Riyadh', 'الرياض'], 
['Sidi Salem', 'سيدى سالم'], 
		]],
		'29'=>[['Luxor', 'الأقصر'],[
['Armant', 'أرمنت'], 
['Bayadeya', 'البياضية'], 
['Isna', 'إسنا'], 
['Luxor City', 'مدينة الأقصر'], 
['Qurna', 'القرنه'], 
['Tod', 'الطود'], 
['Zinnia', 'الزينية'], 
		]],
		'33'=>[['Matruh', 'مطروح'],[
['Alamein', 'العلمين'], 
['Barany', 'براني'], 
['Dabaa', 'الضبعة'], 
['Hammam', 'الحمام'], 
['Marsa Matrouh', 'مرسى مطروح'], 
['Nagela', 'النجيلة'], 
['Salloum', 'السلوم'], 
['Siwa', 'سيوة'], 
		]],
		'24'=>[['Minya', 'المنيا'],[
['Abu Qurqas', 'أبو قرقاص'], 
['Adwa', 'العدوة'], 
['Beni Mazar', 'بني مزار'], 
['Deir Mawas', 'دير مواس'], 
['Maghagha', 'مغاغة'], 
['Malawi', 'ملوي'], 
['Matay', 'مطاي'], 
['Minya City', 'مدينة المنيا'], 
['New Minya', 'المنيا الجديدة'], 
['Samalut', 'سمالوط'], 
		]],
		'17'=>[['Monufia', 'المنوفية'],[
['Ashmon', 'أشمون'], 
['Bagour', 'الباجور'], 
['Berket al Sabaa', 'بركة السبع'], 
['Menouf', 'منوف'], 
['Quesna', 'قويسنا'], 
['Sadat', 'السادات'], 
['Sers al Lyan', 'سرس الليان'], 
['Shebin al Koum', 'شبين الكوم'], 
['Shohadaa', 'الشهداء'], 
['Tala', 'تلا'], 
		]],
		'32'=>[['New Valley', 'الوادي الجديد'],[
['Balat', 'بلاط'], 
['Dakhla', 'الداخلة'], 
['Farafra', 'الفرافرة'], 
['Kharga', 'الخارجة'], 
['Mut', 'مدينة موط'], 
['Paris', 'باريس'], 
		]],
		'34'=>[['North Sinai', 'شمال سيناء'],[
['Arish', 'العريش'], 
['Bir al Abed', 'بئر العبد'], 
['Hasana', 'الحسنة'], 
['Nakhl', 'نخل'], 
['Rafah', 'رفح'], 
['Sheikh Zoweyd', 'الشيخ زويد'], 
		]],
		'03'=>[['Port Said', 'بورسعيد'],[
['Arab District', 'حي العرب'], 
['Dawahy District', 'حي الضواحي'], 
['Ganoub District', 'حي الجنوب'], 
['Manakh District', 'حي المناخ'], 
['Port Fouad', 'مدينة بورفؤاد'], 
['Sharq District', 'حي الشرق'], 
['Zohour District', 'حي الزهور'], 
		]],
		'14'=>[['Qalyubia', 'القليوبية'],[
['Bahtim', 'بهتيم'], 
['Banha', 'بنها'], 
['El Ubour', 'العبور'], 
['Kafr Shukr', 'كفر شكر'], 
['Khanka', 'الخانكة'], 
['Khosous', 'الخصوص'], 
['Qaha', 'قها'], 
['Qalyub', 'قليوب'], 
['Qanater al Khairia', 'القناطر الخيرية'], 
['Shebin al Qanater', 'شبين القناطر'], 
['Shubra al Khaimah', 'شبرا الخيمة'], 
['Tookh', 'طوخ'], 
		]],
		'27'=>[['Qena', 'قنا'],[
['Abu Tisht', 'أبو تشت'], 
['Farshout', 'فرشوط'], 
['Keft', 'قفط'], 
['Nag Hammadi', 'نجع حمادي'], 
['Nakada', 'نقادة'], 
['Qena City', 'مدينة قنا'], 
['Quos', 'قوص'], 
['Shna', 'شنا'], 
['Wakf', 'الوقف'], 
		]],
		'31'=>[['Red Sea', 'البحر الأحمر'],[
['الغردقة', 'الغردقة'], 
['مرسى علم', 'مرسى علم'], 
['القصير', 'القصير'], 
['رأس غارب', 'رأس غارب'], 
['سفاجا', 'سفاجا'], 
['شلاتين', 'شلاتين'], 
		]],
		'13'=>[['Sharqia', 'الشرقية'],[
['10th of Ramadan', 'العاشر من رمضان'], 
['Abu Hammad', 'أبو حماد'], 
['Abu Kabir', 'أبو كبير'], 
['Alqnayat', 'القنايات'], 
['Awlad Saqr', 'أولاد صقر'], 
['Bilbeis', 'بلبيس'], 
['Deyerb Negm', 'ديرب نجم'], 
['Faqous', 'فاقوس'], 
['Hihya', 'ههيا'], 
['Husseiniya', 'الحسينية'], 
['Ibrahemyah', 'الإبراهيمية'], 
['Kafr Saqr', 'كفر صقر'], 
['Mashtool al Souk', 'مشتول السوق'], 
['Minya al Qamh', 'منيا القمح'], 
['New Salhia', 'الصالحية الجديدة'], 
['Qareen', 'القرين'], 
['Zagazig', 'الزقازيق'], 
		]],
		'26'=>[['Sohag', 'سوهاج'],[
['Akhmim', 'أخميم'], 
['Alasirat', 'العسيرات'], 
['Baliana', 'البلينا'], 
['Dar es Salam', 'دارالسلام'], 
['Girga', 'جرجا'], 
['Juhaynah', 'جهينة'], 
['Maragha', 'المراغة'],  
['Sakaltah', 'ساقلتة'], 
['Sohag City', 'مدينة سوهاج'], 
['Tahta', 'طهطا'], 
['Tama', 'طما'], 
		]],
		'35'=>[['South Sinai', 'جنوب سيناء'],[
['Abu Rudeis', 'أبو رديس'], 
['Abu Zenimah', 'أبو زنيمة'], 
['Dahab', 'دهب'], 
['Nuweiba', 'نويبع'], 
['Ras Sidr', 'رأس سدر'], 
['Sharm al Sheikh', 'شرم الشيخ'], 
['St. Catherine', 'سانت كاترين'], 
['Taba', 'طابا'], 
['Tor Sinai', 'طور سيناء'], 
		]],
		'04'=>[['Suez', 'السويس'],[
['Ain Sukhna', 'العين السخنة'], 
['Arbaeen', 'حي الأربعين'], 
['Attaka', 'حي عتاقة'], 
['Faisal', 'فيصل'], 
['Ganayen', 'حى الجناين'], 
['Suez District', 'حي السويس'], 
		]],
];



?>