<?php

/*--------------------------------------------------------------
  		Currency:-
--------------------------------------------------------------*/	
$currency = [
	'EGP' => [
		'code' => 'EGP',
		'name' => 'Egyptian Pound -- الجنيه المصرى',
		'format' => 'EGP',
	],'USD' => [
		'code' => 'USD',
		'name' => 'US Dollar -- الدولار الأمريكى',
		'format' => '$',
	],'SAR' => [
		'code' => 'SAR',
		'name' => 'Saudi Riyal -- الريال السعودى',
		'format' => 'SAR',	
	],'IQD' => [
		'code' => 'IQD',
		'name' => 'Iraqi Dinar -- الدينار العراقى',
		'format' => 'IQD',	
	],'KWD' => [
		'code' => 'KWD',
		'name' => 'Kuwaiti Dinar  -- الدينار الكويتى',
		'format' => 'KWD',
	],'AED' => [
		'code' => 'AED',
		'name' => 'United Arab Emirates Dirham -- الدرهم الإماراتى',
		'format' => 'AED',
	],'AFN' => [
		'code' => 'AFN',
		'name' => 'Afghan Afghani',
		'format' => 'AFN',
	],'ALL' => [
		'code' => 'ALL',
		'name' => 'Albanian Lek',
		'format' => 'ALL',
	],'AMD' => [
		'code' => 'AMD',
		'name' => 'Armenian Dram',
		'format' => 'AMD',
	],'ANG' => [
		'code' => 'ANG',
		'name' => 'Netherlands Antillean Guilder',
		'format' => 'ANG',
	],'AOA' => [
		'code' => 'AOA',
		'name' => 'Angolan Kwanza',
		'format' => 'AOA',
	],'ARS' => [
		'code' => 'ARS',
		'name' => 'Argentine Peso',
		'format' => 'ARS',
	],'AUD' => [
		'code' => 'AUD',
		'name' => 'Australian Dollar',
		'format' => 'A$',
	],'AWG' => [
		'code' => 'AWG',
		'name' => 'Aruban Florin',
		'format' => 'AWG',
	],'AZN' => [
		'code' => 'AZN',
		'name' => 'Azerbaijani Manat',
		'format' => 'AZN',
	],'BAM' => [
		'code' => 'BAM',
		'name' => 'Bosnia-Herzegovina Convertible Mark',
		'format' => 'BAM',
	],'BBD' => [
		'code' => 'BBD',
		'name' => 'Barbadian Dollar',
		'format' => 'BBD',
	],'BDT' => [
		'code' => 'BDT',
		'name' => 'Bangladeshi Taka',
		'format' => 'BDT',
	],'BGN' => [
		'code' => 'BGN',
		'name' => 'Bulgarian Lev',
		'format' => 'BGN',
	],'BHD' => [
		'code' => 'BHD',
		'name' => 'Bahraini Dinar',
		'format' => 'BHD',
	],'BIF' => [
		'code' => 'BIF',
		'name' => 'Burundian Franc',
		'format' => 'BIF',
	],'BMD' => [
		'code' => 'BMD',
		'name' => 'Bermudan Dollar',
		'format' => 'BMD',
	],'BND' => [
		'code' => 'BND',
		'name' => 'Brunei Dollar',
		'format' => 'BND',
	],'BOB' => [
		'code' => 'BOB',
		'name' => 'Bolivian Boliviano',
		'format' => 'BOB',
	],'BRL' => [
		'code' => 'BRL',
		'name' => 'Brazilian Real',
		'format' => 'R$',
	],'BSD' => [
		'code' => 'BSD',
		'name' => 'Bahamian Dollar',
		'format' => 'BSD',
	],'BTC' => [
		'code' => 'BTC',
		'name' => 'Bitcoin',
		'format' => '฿',
	],'BTN' => [
		'code' => 'BTN',
		'name' => 'Bhutanese Ngultrum',
		'format' => 'BTN',
	],'BWP' => [
		'code' => 'BWP',
		'name' => 'Botswanan Pula',
		'format' => 'BWP',
	],'BYR' => [
		'code' => 'BYR',
		'name' => 'Belarusian Ruble',
		'format' => 'BYR',
	],'BZD' => [
		'code' => 'BZD',
		'name' => 'Belize Dollar',
		'format' => 'BZD',
	],'CAD' => [
		'code' => 'CAD',
		'name' => 'Canadian Dollar',
		'format' => 'CA$',
	],'CDF' => [
		'code' => 'CDF',
		'name' => 'Congolese Franc',
		'format' => 'CDF',
	],'CHF' => [
		'code' => 'CHF',
		'name' => 'Swiss Franc',
		'format' => 'CHF',
	],'CLF' => [
		'code' => 'CLF',
		'name' => 'Chilean Unit of Account',
		'format' => 'CLF',
	],'CLP' => [
		'code' => 'CLP',
		'name' => 'Chilean Peso',
		'format' => 'CLP',
	],'CNH' => [
		'code' => 'CNH',
		'name' => 'CNH',
		'format' => 'CNH',
	],'CNY' => [
		'code' => 'CNY',
		'name' => 'Chinese Yuan',
		'format' => 'CN¥',
	],'COP' => [
		'code' => 'COP',
		'name' => 'Colombian Peso',
		'format' => 'COP',
	],'CRC' => [
		'code' => 'CRC',
		'name' => 'Costa Rican Colón',
		'format' => 'CRC',
	],'CUP' => [
		'code' => 'CUP',
		'name' => 'Cuban Peso',
		'format' => 'CUP',
	],'CVE' => [
		'code' => 'CVE',
		'name' => 'Cape Verdean Escudo',
		'format' => 'CVE',
	],'CZK' => [
		'code' => 'CZK',
		'name' => 'Czech Republic Koruna',
		'format' => 'CZK',
	],'DEM' => [
		'code' => 'DEM',
		'name' => 'German Mark',
		'format' => 'DEM',
	],'DJF' => [
		'code' => 'DJF',
		'name' => 'Djiboutian Franc',
		'format' => 'DJF',
	],'DKK' => [
		'code' => 'DKK',
		'name' => 'Danish Krone',
		'format' => 'DKK',
	],'DOP' => [
		'code' => 'DOP',
		'name' => 'Dominican Peso',
		'format' => 'DOP',
	],'DZD' => [
		'code' => 'DZD',
		'name' => 'Algerian Dinar',
		'format' => 'DZD',
	],'ERN' => [
		'code' => 'ERN',
		'name' => 'Eritrean Nakfa',
		'format' => 'ERN',
	],'ETB' => [
		'code' => 'ETB',
		'name' => 'Ethiopian Birr',
		'format' => 'ETB',
	],'EUR' => [
		'code' => 'EUR',
		'name' => 'Euro',
		'format' => '€',
	],'FIM' => [
		'code' => 'FIM',
		'name' => 'Finnish Markka',
		'format' => 'FIM',
	],'FJD' => [
		'code' => 'FJD',
		'name' => 'Fijian Dollar',
		'format' => 'FJD',
	],'FKP' => [
		'code' => 'FKP',
		'name' => 'Falkland Islands Pound',
		'format' => 'FKP',
	],'FRF' => [
		'code' => 'FRF',
		'name' => 'French Franc',
		'format' => 'FRF',
	],'GBP' => [
		'code' => 'GBP',
		'name' => 'British Pound Sterling',
		'format' => '£',
	],'GEL' => [
		'code' => 'GEL',
		'name' => 'Georgian Lari',
		'format' => 'GEL',
	],'GHS' => [
		'code' => 'GHS',
		'name' => 'Ghanaian Cedi',
		'format' => 'GHS',
	],'GIP' => [
		'code' => 'GIP',
		'name' => 'Gibraltar Pound',
		'format' => 'GIP',
	],'GMD' => [
		'code' => 'GMD',
		'name' => 'Gambian Dalasi',
		'format' => 'GMD',
	],'GNF' => [
		'code' => 'GNF',
		'name' => 'Guinean Franc',
		'format' => 'GNF',
	],'GTQ' => [
		'code' => 'GTQ',
		'name' => 'Guatemalan Quetzal',
		'format' => 'GTQ',
	],'GYD' => [
		'code' => 'GYD',
		'name' => 'Guyanaese Dollar',
		'format' => 'GYD',
	],'HKD' => [
		'code' => 'HKD',
		'name' => 'Hong Kong Dollar',
		'format' => 'HK$',
	],'HNL' => [
		'code' => 'HNL',
		'name' => 'Honduran Lempira',
		'format' => 'HNL',
	],'HRK' => [
		'code' => 'HRK',
		'name' => 'Croatian Kuna',
		'format' => 'HRK',
	],'HTG' => [
		'code' => 'HTG',
		'name' => 'Haitian Gourde',
		'format' => 'HTG',
	],'H' => [
		'code' => 'H',
		'name' => 'Hungarian Forint',
		'format' => 'H',
	],'IDR' => [
		'code' => 'IDR',
		'name' => 'Indonesian Rupiah',
		'format' => 'IDR',
	],'IEP' => [
		'code' => 'IEP',
		'name' => 'Irish Pound',
		'format' => 'IEP',
	],'ILS' => [
		'code' => 'ILS',
		'name' => 'Israeli New Sheqel',
		'format' => '₪',
	],'INR' => [
		'code' => 'INR',
		'name' => 'Indian Rupee',
		'format' => 'Rs.',
	],'IRR' => [
		'code' => 'IRR',
		'name' => 'Iranian Rial',
		'format' => 'IRR',
	],'ISK' => [
		'code' => 'ISK',
		'name' => 'Icelandic Króna',
		'format' => 'ISK',
	],'ITL' => [
		'code' => 'ITL',
		'name' => 'Italian Lira',
		'format' => 'ITL',
	],'JMD' => [
		'code' => 'JMD',
		'name' => 'Jamaican Dollar',
		'format' => 'JMD',
	],'JOD' => [
		'code' => 'JOD',
		'name' => 'Jordanian Dinar',
		'format' => 'JOD',
	],'JPY' => [
		'code' => 'JPY',
		'name' => 'Japanese Yen',
		'format' => '¥',
	],'KES' => [
		'code' => 'KES',
		'name' => 'Kenyan Shilling',
		'format' => 'KES',
	],'KGS' => [
		'code' => 'KGS',
		'name' => 'Kyrgystani Som',
		'format' => 'KGS',
	],'KHR' => [
		'code' => 'KHR',
		'name' => 'Cambodian Riel',
		'format' => 'KHR',
	],'KMF' => [
		'code' => 'KMF',
		'name' => 'Comorian Franc',
		'format' => 'KMF',
	],'KPW' => [
		'code' => 'KPW',
		'name' => 'North Korean Won',
		'format' => 'KPW',
	],'KRW' => [
		'code' => 'KRW',
		'name' => 'South Korean Won',
		'format' => '₩',
	],'KYD' => [
		'code' => 'KYD',
		'name' => 'Cayman Islands Dollar',
		'format' => 'KYD',
	],'KZT' => [
		'code' => 'KZT',
		'name' => 'Kazakhstani Tenge',
		'format' => 'KZT',
	],'LAK' => [
		'code' => 'LAK',
		'name' => 'Laotian Kip',
		'format' => 'LAK',
	],'LBP' => [
		'code' => 'LBP',
		'name' => 'Lebanese Pound',
		'format' => 'LBP',
	],'LKR' => [
		'code' => 'LKR',
		'name' => 'Sri Lankan Rupee',
		'format' => 'LKR',
	],'LRD' => [
		'code' => 'LRD',
		'name' => 'Liberian Dollar',
		'format' => 'LRD',
	],'LSL' => [
		'code' => 'LSL',
		'name' => 'Lesotho Loti',
		'format' => 'LSL',
	],'LTL' => [
		'code' => 'LTL',
		'name' => 'Lithuanian Litas',
		'format' => 'LTL',
	],'LVL' => [
		'code' => 'LVL',
		'name' => 'Latvian Lats',
		'format' => 'LVL',
	],'LYD' => [
		'code' => 'LYD',
		'name' => 'Libyan Dinar',
		'format' => 'LYD',
	],'MAD' => [
		'code' => 'MAD',
		'name' => 'Moroccan Dirham',
		'format' => 'MAD',
	],'MDL' => [
		'code' => 'MDL',
		'name' => 'Moldovan Leu',
		'format' => 'MDL',
	],'MGA' => [
		'code' => 'MGA',
		'name' => 'Malagasy Ariary',
		'format' => 'MGA',
	],'MKD' => [
		'code' => 'MKD',
		'name' => 'Macedonian Denar',
		'format' => 'MKD',
	],'MMK' => [
		'code' => 'MMK',
		'name' => 'Myanmar Kyat',
		'format' => 'MMK',
	],'MNT' => [
		'code' => 'MNT',
		'name' => 'Mongolian Tugrik',
		'format' => 'MNT',
	],'MOP' => [
		'code' => 'MOP',
		'name' => 'Macanese Pataca',
		'format' => 'MOP',
	],'MRO' => [
		'code' => 'MRO',
		'name' => 'Mauritanian Ouguiya',
		'format' => 'MRO',
	],'MUR' => [
		'code' => 'MUR',
		'name' => 'Mauritian Rupee',
		'format' => 'MUR',
	],'MVR' => [
		'code' => 'MVR',
		'name' => 'Maldivian Rufiyaa',
		'format' => 'MVR',
	],'MWK' => [
		'code' => 'MWK',
		'name' => 'Malawian Kwacha',
		'format' => 'MWK',
	],'MXN' => [
		'code' => 'MXN',
		'name' => 'Mexican Peso',
		'format' => 'MX$',
	],'MYR' => [
		'code' => 'MYR',
		'name' => 'Malaysian Ringgit',
		'format' => 'MYR',
	],'MZN' => [
		'code' => 'MZN',
		'name' => 'Mozambican Metical',
		'format' => 'MZN',
	],'NAD' => [
		'code' => 'NAD',
		'name' => 'Namibian Dollar',
		'format' => 'NAD',
	],'NGN' => [
		'code' => 'NGN',
		'name' => 'Nigerian Naira',
		'format' => 'NGN',
	],'NIO' => [
		'code' => 'NIO',
		'name' => 'Nicaraguan Córdoba',
		'format' => 'NIO',
	],'NOK' => [
		'code' => 'NOK',
		'name' => 'Norwegian Krone',
		'format' => 'NOK',
	],'NPR' => [
		'code' => 'NPR',
		'name' => 'Nepalese Rupee',
		'format' => 'NPR',
	],'NZD' => [
		'code' => 'NZD',
		'name' => 'New Zealand Dollar',
		'format' => 'NZ$',
	],'OMR' => [
		'code' => 'OMR',
		'name' => 'Omani Rial',
		'format' => 'OMR',
	],'PAB' => [
		'code' => 'PAB',
		'name' => 'Panamanian Balboa',
		'format' => 'PAB',
	],'PEN' => [
		'code' => 'PEN',
		'name' => 'Peruvian Nuevo Sol',
		'format' => 'PEN',
	],'PGK' => [
		'code' => 'PGK',
		'name' => 'Papua New Guinean Kina',
		'format' => 'PGK',
	],'PHP' => [
		'code' => 'PHP',
		'name' => 'Philippine Peso',
		'format' => 'Php',
	],'PKG' => [
		'code' => 'PKG',
		'name' => 'PKG',
		'format' => 'PKG',
	],'PKR' => [
		'code' => 'PKR',
		'name' => 'Pakistani Rupee',
		'format' => 'PKR',
	],'PLN' => [
		'code' => 'PLN',
		'name' => 'Polish Zloty',
		'format' => 'PLN',
	],'PYG' => [
		'code' => 'PYG',
		'name' => 'Paraguayan Guarani',
		'format' => 'PYG',
	],'QAR' => [
		'code' => 'QAR',
		'name' => 'Qatari Rial',
		'format' => 'QAR',
	],'RON' => [
		'code' => 'RON',
		'name' => 'Romanian Leu',
		'format' => 'RON',
	],'RSD' => [
		'code' => 'RSD',
		'name' => 'Serbian Dinar',
		'format' => 'RSD',
	],'RUB' => [
		'code' => 'RUB',
		'name' => 'Russian Ruble',
		'format' => 'RUB',
	],'RWF' => [
		'code' => 'RWF',
		'name' => 'Rwandan Franc',
		'format' => 'RWF',
	],'SBD' => [
		'code' => 'SBD',
		'name' => 'Solomon Islands Dollar',
		'format' => 'SBD',
	],'SCR' => [
		'code' => 'SCR',
		'name' => 'Seychellois Rupee',
		'format' => 'SCR',
	],'SDG' => [
		'code' => 'SDG',
		'name' => 'Sudanese Pound',
		'format' => 'SDG',
	],'SEK' => [
		'code' => 'SEK',
		'name' => 'Swedish Krona',
		'format' => 'SEK',
	],'SGD' => [
		'code' => 'SGD',
		'name' => 'Singapore Dollar',
		'format' => 'SGD',
	],'SHP' => [
		'code' => 'SHP',
		'name' => 'Saint Helena Pound',
		'format' => 'SHP',
	],'SLL' => [
		'code' => 'SLL',
		'name' => 'Sierra Leonean Leone',
		'format' => 'SLL',
	],'SOS' => [
		'code' => 'SOS',
		'name' => 'Somali Shilling',
		'format' => 'SOS',
	],'SRD' => [
		'code' => 'SRD',
		'name' => 'Surinamese Dollar',
		'format' => 'SRD',
	],'STD' => [
		'code' => 'STD',
		'name' => 'São Tomé and Príncipe Dobra',
		'format' => 'STD',
	],'SVC' => [
		'code' => 'SVC',
		'name' => 'Salvadoran Colón',
		'format' => 'SVC',
	],'SYP' => [
		'code' => 'SYP',
		'name' => 'Syrian Pound',
		'format' => 'SYP',
	],'SZL' => [
		'code' => 'SZL',
		'name' => 'Swazi Lilangeni',
		'format' => 'SZL',
	],'THB' => [
		'code' => 'THB',
		'name' => 'Thai Baht',
		'format' => '฿',
	],'TJS' => [
		'code' => 'TJS',
		'name' => 'Tajikistani Somoni',
		'format' => 'TJS',
	],'TMT' => [
		'code' => 'TMT',
		'name' => 'Turkmenistani Manat',
		'format' => 'TMT',
	],'TND' => [
		'code' => 'TND',
		'name' => 'Tunisian Dinar',
		'format' => 'TND',
	],'TOP' => [
		'code' => 'TOP',
		'name' => 'Tongan Paʻanga',
		'format' => 'TOP',
	],'TRY' => [
		'code' => 'TRY',
		'name' => 'Turkish Lira',
		'format' => 'TRY',
	],'TTD' => [
		'code' => 'TTD',
		'name' => 'Trinidad and Tobago Dollar',
		'format' => 'TTD',
	],'TWD' => [
		'code' => 'TWD',
		'name' => 'New Taiwan Dollar',
		'format' => 'NT$',
	],'TZS' => [
		'code' => 'TZS',
		'name' => 'Tanzanian Shilling',
		'format' => 'TZS',
	],'UAH' => [
		'code' => 'UAH',
		'name' => 'Ukrainian Hryvnia',
		'format' => 'UAH',
	],'UGX' => [
		'code' => 'UGX',
		'name' => 'Ugandan Shilling',
		'format' => 'UGX',
	],'UYU' => [
		'code' => 'UYU',
		'name' => 'Uruguayan Peso',
		'format' => 'UYU',
	],'UZS' => [
		'code' => 'UZS',
		'name' => 'Uzbekistan Som',
		'format' => 'UZS',
	],'VEF' => [
		'code' => 'VEF',
		'name' => 'Venezuelan Bolívar',
		'format' => 'VEF',
	],'VND' => [
		'code' => 'VND',
		'name' => 'Vietnamese Dong',
		'format' => '₫',
	],'VUV' => [
		'code' => 'VUV',
		'name' => 'Vanuatu Vatu',
		'format' => 'VUV',
	],'WST' => [
		'code' => 'WST',
		'name' => 'Samoan Tala',
		'format' => 'WST',
	],'XAF' => [
		'code' => 'XAF',
		'name' => 'CFA Franc BEAC',
		'format' => 'FCFA',
	],'XCD' => [
		'code' => 'XCD',
		'name' => 'East Caribbean Dollar',
		'format' => 'EC$',
	],'XDR' => [
		'code' => 'XDR',
		'name' => 'Special Drawing Rights',
		'format' => 'XDR',
	],'XOF' => [
		'code' => 'XOF',
		'name' => 'CFA Franc BCEAO',
		'format' => 'CFA',
	],'XPF' => [
		'code' => 'XPF',
		'name' => 'CFP Franc',
		'format' => 'CFPF',
	],'YER' => [
		'code' => 'YER',
		'name' => 'Yemeni Rial',
		'format' => 'YER',
	],'ZAR' => [
		'code' => 'ZAR',
		'name' => 'South African Rand',
		'format' => 'ZAR',
	],'ZMK' => [
		'code' => 'ZMK',
		'name' => 'Zambian Kwacha',
		'format' => 'ZMK',
	],'ZMW' => [
		'code' => 'ZMW',
		'name' => 'Zambian Kwacha',
		'format' => 'ZMW',
	],'ZWL' => [
		'code' => 'ZWL',
		'name' => 'Zimbabwean Dollar',
		'format' => 'ZWL',
	],
];

?>