<?php 

/********************************Postal Codes**************************************/
$postal_codes = array ( 
	0 => array ( 'postal_code' => '11518', 'post_office' => 'محمد فريد', 'address' => '1 شارع محمد فريد /القاهره', 'postal_area' => 'وسط وشمال القاهره', ), 
	1 => array ( 'postal_code' => '11549', 'post_office' => 'ارض السبيل', 'address' => 'ش ورش التليفونات شبرا', 'postal_area' => 'وسط وشمال القاهره', ), 
	2 => array ( 'postal_code' => '11558', 'post_office' => 'باب الشعريه', 'address' => '178 ش الجيش / باب الشعريه', 'postal_area' => 'وسط وشمال القاهره', ), 
	3 => array ( 'postal_code' => '11563', 'post_office' => 'الظاهر', 'address' => '70 شارع الظاهر', 'postal_area' => 'وسط وشمال القاهره', ), 
	4 => array ( 'postal_code' => '11577', 'post_office' => 'القبيسي', 'address' => '39 ش اسماعيل الفلكي / الظاهر', 'postal_area' => 'وسط وشمال القاهره', ), 
	5 => array ( 'postal_code' => '11599', 'post_office' => 'القاهره الرئيسي', 'address' => 'ميدان العتبه/1ش عبد الخالق ثروت', 'postal_area' => 'وسط وشمال القاهره', ), 
	6 => array ( 'postal_code' => '11611', 'post_office' => 'بولاق', 'address' => '74 ش 26 يوليو القاهره/بولاق', 'postal_area' => 'وسط وشمال القاهره', ), 
	7 => array ( 'postal_code' => '11621', 'post_office' => 'الخرنفش', 'address' => '4 ش الخرنفش بالجماليه', 'postal_area' => 'وسط وشمال القاهره', ), 
	8 => array ( 'postal_code' => '11633', 'post_office' => 'الدراسه', 'address' => '9ش المنصوريه بالدراسه/الجماليه', 'postal_area' => 'وسط وشمال القاهره', ), 
	9 => array ( 'postal_code' => '11639', 'post_office' => 'الغوريه', 'address' => '4 ش السلطان الصاحب بالغوريه /الدرب الاحمر', 'postal_area' => 'وسط وشمال القاهره', ), 
	10 => array ( 'postal_code' => '11642', 'post_office' => 'مبني التوفير بالازبكيه', 'address' => 'مبني التوفير بالازبكيه', 'postal_area' => 'وسط وشمال القاهره', ), 
	11 => array ( 'postal_code' => '11668', 'post_office' => 'باب البحر', 'address' => '36 ش باب البحر / باب الشعريه', 'postal_area' => 'وسط وشمال القاهره', ), 
	12 => array ( 'postal_code' => '11674', 'post_office' => 'غمره', 'address' => '4 ش ميدان السكاكيني', 'postal_area' => 'وسط وشمال القاهره', ), 
	13 => array ( 'postal_code' => '11675', 'post_office' => 'الازهر', 'address' => '123 ش الازهر/ قسم الجماليه', 'postal_area' => 'وسط وشمال القاهره', ), 
	14 => array ( 'postal_code' => '11676', 'post_office' => 'اسكان اطلس', 'address' => 'مساكن اطلس/الزاويه بلوك 98', 'postal_area' => 'وسط وشمال القاهره', ), 
	15 => array ( 'postal_code' => '12211', 'post_office' => 'الجيزه / توزيع', 'address' => 'رقم البريد الرئيسي لمحافظه الجيزه', 'postal_area' => 'الجيزه', ), 
	16 => array ( 'postal_code' => '12511', 'post_office' => 'الجيزه / مصالح', 'address' => 'رقم البريد الرئيسي لمحافظه الجيزه', 'postal_area' => 'الجيزه', ), 
	17 => array ( 'postal_code' => '12513', 'post_office' => 'الجيزه ثان', 'address' => '10 ش الصناديلي / الجيزه', 'postal_area' => 'الجيزه', ), 
	18 => array ( 'postal_code' => '12514', 'post_office' => 'سوق الاحد', 'address' => 'شارع المحطه / م. الجيزه', 'postal_area' => 'الجيزه', ), 
	19 => array ( 'postal_code' => '12515', 'post_office' => 'الربيع الجيزي', 'address' => 'مبني مجمع المصالح / الجيزه', 'postal_area' => 'الجيزه', ), 
	20 => array ( 'postal_code' => '12516', 'post_office' => 'الجيزه رابع', 'address' => 'المساكن الشعبيه / ساقيه مكي / جيزه', 'postal_area' => 'الجيزه', ), 
	21 => array ( 'postal_code' => '12569', 'post_office' => 'الشيخ عتمان', 'address' => 'مبني الحزب الوطني بقريه الشيخ عتمان / م. الجيزه', 'postal_area' => 'جنوب اكتوبر', ), 
	22 => array ( 'postal_code' => '12576', 'post_office' => 'عثمان احمد عثمان', 'address' => 'قريه الحرانيه/ م ابو النمرس/ الجيزه', 'postal_area' => 'جنوب اكتوبر', ), 
	23 => array ( 'postal_code' => '12654', 'post_office' => 'العجوزه', 'address' => '/ العجوزهش/ ابو المعالي الشاذلي', 'postal_area' => 'الجيزه', ), 
	24 => array ( 'postal_code' => '12677', 'post_office' => 'المنطقه الصناعيه / ابو رواش', 'address' => 'الجيزه / امام القريه الزكيه / الكيلو 28 طريق', 'postal_area' => 'شمال اكتوبر', ), 
	25 => array ( 'postal_code' => '12882', 'post_office' => 'عرب الساحه', 'address' => 'عرب الساحه / الجيزه', 'postal_area' => 'جنوب اكتوبر', ), 
	26 => array ( 'postal_code' => '12911', 'post_office' => 'ابو النمرس', 'address' => 'ابو النمرس / بجوار شرطه الجيزه', 'postal_area' => 'جنوب اكتوبر', ), 
	27 => array ( 'postal_code' => '12912', 'post_office' => 'منيل شيحه', 'address' => 'ش الوحده المحليه/الجيزه/ابو النمرس', 'postal_area' => 'جنوب اكتوبر', ), 
	28 => array ( 'postal_code' => '12913', 'post_office' => 'طموه', 'address' => 'الوحده المحليه بقريه طموه م . الجيزه', 'postal_area' => 'جنوب اكتوبر', ), 
	29 => array ( 'postal_code' => '12945', 'post_office' => 'صفط اللبن', 'address' => 'صفط اللبن / الجيزه/ م. امبابه عتمان / م . الجيزه', 'postal_area' => 'شمال اكتوبر', ), 
	30 => array ( 'postal_code' => '12997', 'post_office' => 'صيدا والقيراطين', 'address' => 'قريه القيراطين الجيزه', 'postal_area' => 'شمال اكتوبر', ), 
	31 => array ( 'postal_code' => '13511', 'post_office' => 'بنها البلد', 'address' => 'ميدان سعد زغلول / بنها', 'postal_area' => 'القليوبيه', ), 
	32 => array ( 'postal_code' => '13512', 'post_office' => 'بنها الجديده', 'address' => 'مدينه بنها قصر الثقافه / ش الحلالي', 'postal_area' => 'القليوبيه', ), 
	33 => array ( 'postal_code' => '13513', 'post_office' => 'منشيه لجديده', 'address' => 'بنها البلد شارع سعد زغلول', 'postal_area' => 'القليوبيه', ), 
	34 => array ( 'postal_code' => '13514', 'post_office' => 'كفر مناقر', 'address' => 'شارع عبد الحافظ / بنها', 'postal_area' => 'القليوبيه', ), 
	35 => array ( 'postal_code' => '13616', 'post_office' => 'بلقس', 'address' => 'قريه بلقس / قليوب', 'postal_area' => 'القليوبيه', ), 
	36 => array ( 'postal_code' => '13621', 'post_office' => 'القناطر الخيريه', 'address' => 'مبني السنترال/ القناطرالخيريه', 'postal_area' => 'القليوبيه', ), 
	37 => array ( 'postal_code' => '13711', 'post_office' => 'شبين القناطر', 'address' => 'المساكن الشعبيه / شبين القناطر', 'postal_area' => 'القليوبيه', ), 
	38 => array ( 'postal_code' => '13713', 'post_office' => 'سندنهور', 'address' => 'قريه سندنهور / بنها', 'postal_area' => 'القليوبيه', ), 
	39 => array ( 'postal_code' => '13714', 'post_office' => 'جمجره الجديده', 'address' => 'قريه جمجره / بنها/ ش النقطه', 'postal_area' => 'القليوبيه', ), 
	40 => array ( 'postal_code' => '13715', 'post_office' => 'اسنيت', 'address' => 'اسنيت كفر شكر', 'postal_area' => 'القليوبيه', ), 
	41 => array ( 'postal_code' => '13716', 'post_office' => 'شبلنجه', 'address' => 'قريه شبلنجه بنها', 'postal_area' => 'القليوبيه', ), 
	42 => array ( 'postal_code' => '13717', 'post_office' => 'بتمده', 'address' => 'قريه بتمده / بنها', 'postal_area' => 'القليوبيه', ), 
	43 => array ( 'postal_code' => '13722', 'post_office' => 'الرمله', 'address' => 'قريه الرمله / مركز بنها', 'postal_area' => 'القليوبيه', ), 
	44 => array ( 'postal_code' => '13723', 'post_office' => 'طحله', 'address' => 'قريه طحله بنها', 'postal_area' => 'القليوبيه', ), 
	45 => array ( 'postal_code' => '13724', 'post_office' => 'دجوي', 'address' => 'قريه دجوي / بنها', 'postal_area' => 'القليوبيه', ), 
	46 => array ( 'postal_code' => '13725', 'post_office' => 'بلتان', 'address' => 'قريه بلتان / طوخ', 'postal_area' => 'القليوبيه', ), 
	47 => array ( 'postal_code' => '13727', 'post_office' => 'العمار', 'address' => 'قريه العمار طوخ', 'postal_area' => 'القليوبيه', ), 
	48 => array ( 'postal_code' => '13729', 'post_office' => 'برشوم الصغري', 'address' => 'قريه برشوم الصغري / طوخ', 'postal_area' => 'القليوبيه', ), 
	49 => array ( 'postal_code' => '13731', 'post_office' => 'اجهور الكبري', 'address' => 'قريه اجهور الكبري / طوخ', 'postal_area' => 'القليوبيه', ), 
	50 => array ( 'postal_code' => '13733', 'post_office' => 'الشموت', 'address' => 'قريه الشموت بنها', 'postal_area' => 'القليوبيه', ), 
	51 => array ( 'postal_code' => '13734', 'post_office' => 'مرصفا', 'address' => 'قريه مرصفا /بنها', 'postal_area' => 'القليوبيه', ), 
	52 => array ( 'postal_code' => '13737', 'post_office' => 'الدير', 'address' => 'مبني الوحده المحليه بالدير / طوخ', 'postal_area' => 'القليوبيه', ), 
	53 => array ( 'postal_code' => '13744', 'post_office' => 'سنديون', 'address' => 'قريه سنديون قليوب', 'postal_area' => 'القليوبيه', ), 
	54 => array ( 'postal_code' => '13748', 'post_office' => 'طحانوب', 'address' => 'قريه طحانوب شبين القناطر/ ش المحطه', 'postal_area' => 'القليوبيه', ), 
	55 => array ( 'postal_code' => '13776', 'post_office' => 'بطا', 'address' => 'قريه بطا / بنها', 'postal_area' => 'القليوبيه', ), 
	56 => array ( 'postal_code' => '13777', 'post_office' => 'كفر الجزار', 'address' => 'قريه كفر الجزار بنها / المساكن الشعبيه', 'postal_area' => 'القليوبيه', ), 
	57 => array ( 'postal_code' => '21516', 'post_office' => 'الحضره قبلي', 'address' => '30ش السراي / باب شرق', 'postal_area' => 'الاسكندريه', ), 
	58 => array ( 'postal_code' => '21517', 'post_office' => 'العطارين', 'address' => 'ش الكاشف العطارين', 'postal_area' => 'الاسكندريه', ), 
	59 => array ( 'postal_code' => '21519', 'post_office' => 'الاسكندريه المنشيه', 'address' => 'ش الغرفه التجاريه / سيدي جابر', 'postal_area' => 'الاسكندريه', ), 
	60 => array ( 'postal_code' => '21521', 'post_office' => 'المسله', 'address' => 'العطارين / 22ش الشهيد مصطفي حافظ', 'postal_area' => 'الاسكندريه', ), 
	61 => array ( 'postal_code' => '21524', 'post_office' => 'الابراهيميه الرمل', 'address' => '112ش عمر لطفي / الابراهيميه', 'postal_area' => 'الاسكندريه', ), 
	62 => array ( 'postal_code' => '21527', 'post_office' => 'باكوس', 'address' => 'ش محطه السوق / الرمل', 'postal_area' => 'الاسكندريه', ), 
	63 => array ( 'postal_code' => '21531', 'post_office' => 'بولكلي', 'address' => 'مبني خفر السواحل / بولكلي / سيدي جابر', 'postal_area' => 'الاسكندريه', ), 
	64 => array ( 'postal_code' => '21533', 'post_office' => 'تفتيش السيوف', 'address' => 'ش جميله ابو حريد / السيوف / المنتزه', 'postal_area' => 'الاسكندريه', ), 
	65 => array ( 'postal_code' => '21534', 'post_office' => 'جمرك اسكندريهالمكس', 'address' => 'مبني اداره الجمارك / ميناءالاسكندريه', 'postal_area' => 'الاسكندريه', ), 
	66 => array ( 'postal_code' => '21562', 'post_office' => 'الميدان', 'address' => 'ش حسن توفيق / المنشيه', 'postal_area' => 'الاسكندريه', ), 
	67 => array ( 'postal_code' => '21912', 'post_office' => 'المعموره', 'address' => 'مبني السكه الحديد / المنتزه', 'postal_area' => 'الاسكندريه', ), 
	68 => array ( 'postal_code' => '21913', 'post_office' => 'ابوقير', 'address' => 'مبني محطه سكه حديد ابو قير', 'postal_area' => 'الاسكندريه', ), 
	69 => array ( 'postal_code' => '21918', 'post_office' => 'حجر النواتيه', 'address' => '137ش حجر النواتيه / الرمل', 'postal_area' => 'الاسكندريه', ), 
	70 => array ( 'postal_code' => '21919', 'post_office' => 'المنتزه', 'address' => 'مبني السكه الحديد / المنتزه', 'postal_area' => 'الاسكندريه', ), 
	71 => array ( 'postal_code' => '21923', 'post_office' => 'المندره', 'address' => 'ش ملك حنفي / المنتزه', 'postal_area' => 'الاسكندريه', ), 
	72 => array ( 'postal_code' => '22511', 'post_office' => 'دمنهور', 'address' => 'ش المديريه -ميدان المحطه - دمنهور', 'postal_area' => 'البحيره', ), 
	73 => array ( 'postal_code' => '22514', 'post_office' => 'العباره', 'address' => 'ش مصطفي كامل -بجوار مباحث امن الدوله - دمنهور', 'postal_area' => 'البحيره', ), 
	74 => array ( 'postal_code' => '22611', 'post_office' => 'ابوحمص ', 'address' => 'المحطه - مدينه ابو حمص ', 'postal_area' => 'البحيره', ), 
	75 => array ( 'postal_code' => '22612', 'post_office' => 'ابوحمص  البلد', 'address' => 'شارع ناصر - مدينه ابو حمص ', 'postal_area' => 'البحيره', ), 
	76 => array ( 'postal_code' => '22731', 'post_office' => 'ابوالمطامير بحيره', 'address' => 'ش المعهد الجديد - مدينه ابو المطامير', 'postal_area' => 'البحيره', ), 
	77 => array ( 'postal_code' => '22747', 'post_office' => 'البصيلي', 'address' => 'قريه البوصيلي - مركز ادكو شارع المحطه', 'postal_area' => 'البحيره', ), 
	78 => array ( 'postal_code' => '22748', 'post_office' => 'ادكو', 'address' => 'شارع خيرت - مدينه ادكو', 'postal_area' => 'البحيره', ), 
	79 => array ( 'postal_code' => '22758', 'post_office' => 'ادفينا', 'address' => 'مدينه ادفينا شارع البحر /رشيد', 'postal_area' => 'البحيره', ), 
	80 => array ( 'postal_code' => '22777', 'post_office' => 'ابو بكر الصديق', 'address' => 'ش ابو بكر الصديق / مركز بدرالبحيره', 'postal_area' => 'برج العرب', ), 
	81 => array ( 'postal_code' => '22779', 'post_office' => 'احمد بدوي', 'address' => 'ش احمد بدوي - النوباريه - البحيره', 'postal_area' => 'برج العرب', ), 
	82 => array ( 'postal_code' => '22791', 'post_office' => 'الشجاعه', 'address' => 'قريه الشجاعه - البستان - البحيره', 'postal_area' => 'برج العرب', ), 
	83 => array ( 'postal_code' => '22792', 'post_office' => 'قريه الوفاء', 'address' => 'قريه الوفاء - البحيره', 'postal_area' => 'برج العرب', ), 
	84 => array ( 'postal_code' => '22856', 'post_office' => 'وادي النطرون', 'address' => 'ميدان العبور وادي النطرون/ البحيره', 'postal_area' => 'جنوب المنوفيه', ), 
	85 => array ( 'postal_code' => '31511', 'post_office' => 'طنطا مصالح الرئيسي', 'address' => 'ميدان المحطه / طنطا', 'postal_area' => 'الغربيه', ), 
	86 => array ( 'postal_code' => '31512', 'post_office' => 'طنطا فرعي', 'address' => 'ش طه الحكيم / طنطا', 'postal_area' => 'الغربيه', ), 
	87 => array ( 'postal_code' => '31532', 'post_office' => 'كفر المنصوره', 'address' => 'قريه كفر المنصوره / مركز طنطا', 'postal_area' => 'الغربيه', ), 
	88 => array ( 'postal_code' => '31613', 'post_office' => 'ابو الغر', 'address' => 'ابو الغر/م كفر الزيات', 'postal_area' => 'الغربيه', ), 
	89 => array ( 'postal_code' => '31633', 'post_office' => 'الجعفريه', 'address' => 'الجعفريه / مركز السنطه', 'postal_area' => 'الغربيه', ), 
	90 => array ( 'postal_code' => '31649', 'post_office' => 'الغريب', 'address' => 'الغريب/ مركز زفتي', 'postal_area' => 'الغربيه', ), 
	91 => array ( 'postal_code' => '31686', 'post_office' => 'كفر شماخ', 'address' => 'كفر شماخ / مركز كفر الزيات', 'postal_area' => 'الغربيه', ), 
	92 => array ( 'postal_code' => '31711', 'post_office' => 'ابيار', 'address' => 'قريه ابيار/ م كفر الزيات', 'postal_area' => 'الغربيه', ), 
	93 => array ( 'postal_code' => '31724', 'post_office' => 'ابشواي الملق', 'address' => 'مركز قطور', 'postal_area' => 'الغربيه', ), 
	94 => array ( 'postal_code' => '31745', 'post_office' => 'الجميزه', 'address' => 'الجميزه / مركز السنطه', 'postal_area' => 'الغربيه', ), 
	95 => array ( 'postal_code' => '31786', 'post_office' => 'حوين', 'address' => 'قريه حوين – مركز قطور', 'postal_area' => 'الغربيه', ), 
	96 => array ( 'postal_code' => '23724', 'post_office' => 'علي مبارك', 'address' => 'قريه البساتين/البحيره/علي مبارك مركز وادي النطرون', 'postal_area' => 'جنوب المنوفيه', ), 
	97 => array ( 'postal_code' => '32511', 'post_office' => 'شبين الكوم', 'address' => 'ش سعد زغلول شبين الكوم', 'postal_area' => 'شمال المنوفيه', ), 
	98 => array ( 'postal_code' => '32512', 'post_office' => 'شبين الكوم فرعي', 'address' => 'ش المدارس / شبين الكوم', 'postal_area' => 'شمال المنوفيه', ), 
	99 => array ( 'postal_code' => '32611', 'post_office' => 'تلا', 'address' => 'ش الشيخ فؤاد/ تلا', 'postal_area' => 'شمال المنوفيه', ), 
	100 => array ( 'postal_code' => '32613', 'post_office' => 'طوخ دلكا', 'address' => 'ش داير الناحيه طوخ دلكه / تلا', 'postal_area' => 'شمال المنوفيه', ), 
	101 => array ( 'postal_code' => '32631', 'post_office' => 'قويسنا', 'address' => 'ش البوسته / قويسنا', 'postal_area' => 'شمال المنوفيه', ), 
	102 => array ( 'postal_code' => '32633', 'post_office' => 'شبرا بخوم', 'address' => 'قريه شبرا بخوم / قوسينا', 'postal_area' => 'شمال المنوفيه', ), 
	103 => array ( 'postal_code' => '32639', 'post_office' => 'ام خنان', 'address' => 'قريه ام خنان / قويسنا', 'postal_area' => 'شمال المنوفيه', ), 
	104 => array ( 'postal_code' => '32651', 'post_office' => 'بركه السبع', 'address' => 'البر الشرقي / خلف مركز الشباب/ بركه السبع', 'postal_area' => 'شمال المنوفيه', ), 
	105 => array ( 'postal_code' => '32653', 'post_office' => 'جنزور', 'address' => 'ش داير الناحيه جنزور / بركه السبع', 'postal_area' => 'شمال المنوفيه', ), 
	106 => array ( 'postal_code' => '32657', 'post_office' => 'شنتنا الحجر', 'address' => 'ش داير الناحيه شنتنا الحجر / بركه السبع', 'postal_area' => 'شمال المنوفيه', ), 
	107 => array ( 'postal_code' => '32712', 'post_office' => 'شبرا خلفون', 'address' => 'قريه شبرا خلفون / شبين الكوم', 'postal_area' => 'شمال المنوفيه', ), 
	108 => array ( 'postal_code' => '32715', 'post_office' => 'الماي', 'address' => 'ش زيد بن حارثه الماي / شبين الكوم', 'postal_area' => 'شمال المنوفيه', ), 
	109 => array ( 'postal_code' => '32718', 'post_office' => 'شنوان', 'address' => 'قريه شنوان / شبين الكوم', 'postal_area' => 'شمال المنوفيه', ), 
	110 => array ( 'postal_code' => '32719', 'post_office' => 'البتانون محطه', 'address' => 'ش السكه الحديد البتانون / شبين الكوم', 'postal_area' => 'شمال المنوفيه', ), 
	111 => array ( 'postal_code' => '32721', 'post_office' => 'البتانون بلد', 'address' => 'ش الجمهوريه البتانون / شيبن الكوم', 'postal_area' => 'شمال المنوفيه', ), 
	112 => array ( 'postal_code' => '32894', 'post_office' => 'هيت منوفيه', 'address' => 'ميدان العبور وادي النطرون/ البحيره', 'postal_area' => 'جنوب المنوفيه', ), 
	113 => array ( 'postal_code' => '23623', 'post_office' => 'فوه', 'address' => 'ش الفتح', 'postal_area' => 'كفر الشيخ', ), 
	114 => array ( 'postal_code' => '33511', 'post_office' => 'كفر الشيخ', 'address' => 'ش الجيش بجوار مديريه الامن / مركز كفر الشيخ', 'postal_area' => 'كفر الشيخ', ), 
	115 => array ( 'postal_code' => '33611', 'post_office' => 'دسوق', 'address' => 'دسوق بجوار السنترال/حي مكه', 'postal_area' => 'كفر الشيخ', ), 
	116 => array ( 'postal_code' => '33625', 'post_office' => 'مطوبس', 'address' => 'ش بور سعيد/مركز مطوبس', 'postal_area' => 'كفر الشيخ', ), 
	117 => array ( 'postal_code' => '33631', 'post_office' => 'ابو غنيمه', 'address' => 'ابو غنيمه / سيدي سالم', 'postal_area' => 'كفر الشيخ', ), 
	118 => array ( 'postal_code' => '33634', 'post_office' => 'بيلا', 'address' => 'بيلا / ش 23 يوليو', 'postal_area' => 'كفر الشيخ', ), 
	119 => array ( 'postal_code' => '33711', 'post_office' => 'المرابعين', 'address' => 'المرابعين / كفر الشيخ', 'postal_area' => 'كفر الشيخ', ), 
	120 => array ( 'postal_code' => '33713', 'post_office' => 'سيدي غازي', 'address' => 'سيدي غازي / كفر الشيخ', 'postal_area' => 'كفر الشيخ', ), 
	121 => array ( 'postal_code' => '33716', 'post_office' => 'ابشان', 'address' => 'ابشان امام محطه السكه الحديد / مركز بيلا', 'postal_area' => 'كفر الشيخ', ), 
	122 => array ( 'postal_code' => '33717', 'post_office' => 'سخا', 'address' => 'سخا/الشارع العمومي/كفر الشيخ', 'postal_area' => 'كفر الشيخ', ), 
	123 => array ( 'postal_code' => '33721', 'post_office' => 'شباس الشهداء', 'address' => 'شباس الشهداء / دسوق', 'postal_area' => 'كفر الشيخ', ), 
	124 => array ( 'postal_code' => '33723', 'post_office' => 'سنهور المدينه', 'address' => 'سنهور المدينه / دسوق', 'postal_area' => 'كفر الشيخ', ), 
	125 => array ( 'postal_code' => '33729', 'post_office' => 'الحامول براري', 'address' => 'ش ابو بكر الصديق/ مركز الحامول براري', 'postal_area' => 'كفر الشيخ', ), 
	126 => array ( 'postal_code' => '33735', 'post_office' => 'بلطيم', 'address' => 'بلطيم / بجوار السنترال مركز بلطيم', 'postal_area' => 'كفر الشيخ', ), 
	127 => array ( 'postal_code' => '33736', 'post_office' => 'برج البرلس', 'address' => 'برج البرلس / بلطيم', 'postal_area' => 'كفر الشيخ', ), 
	128 => array ( 'postal_code' => '33743', 'post_office' => 'سيدي سالم', 'address' => 'سيدي سالم / مركز سيدي سالم', 'postal_area' => 'كفر الشيخ', ), 
	129 => array ( 'postal_code' => '34511', 'post_office' => 'دمياط الرئيسي', 'address' => 'الكورنيش / دمياط', 'postal_area' => 'دمياط', ), 
	130 => array ( 'postal_code' => '34512', 'post_office' => 'دمياط ثان', 'address' => 'الاعصر- دمياط.مساكن المنيره/مديريه الامن', 'postal_area' => 'دمياط', ), 
	131 => array ( 'postal_code' => '34513', 'post_office' => 'دمياط رابع', 'address' => 'حاره البركه/دمياط', 'postal_area' => 'دمياط', ), 
	132 => array ( 'postal_code' => '34611', 'post_office' => 'فارسكور', 'address' => 'ميدان الشيمي- فارسكور', 'postal_area' => 'دمياط', ), 
	133 => array ( 'postal_code' => '34612', 'post_office' => 'الروضه', 'address' => 'الروضه- مركز فارسكور', 'postal_area' => 'دمياط', ), 
	134 => array ( 'postal_code' => '34621', 'post_office' => 'كفر سعد', 'address' => 'المساكن الاقتصاديه- كفر سعد', 'postal_area' => 'دمياط', ), 
	135 => array ( 'postal_code' => '34622', 'post_office' => 'تفتيش ثان كفر سعد', 'address' => 'الوحده المجمعه- م. كفر سعد', 'postal_area' => 'دمياط', ), 
	136 => array ( 'postal_code' => '34623', 'post_office' => 'كفر سليمان البحري', 'address' => 'كفر سعد/ كفر سليمان البحري', 'postal_area' => 'دمياط', ), 
	137 => array ( 'postal_code' => '34711', 'post_office' => 'راس البر', 'address' => 'المنطقه الاولي راس البر/ش 47', 'postal_area' => 'دمياط', ), 
	138 => array ( 'postal_code' => '34712', 'post_office' => 'عزبه البرج', 'address' => 'عزبه البرج/ مركز دمياط', 'postal_area' => 'دمياط', ), 
	139 => array ( 'postal_code' => '34713', 'post_office' => 'السنانيه', 'address' => 'السنانيه- مركز دمياط/ش الطريق العام', 'postal_area' => 'دمياط', ), 
	140 => array ( 'postal_code' => '34715', 'post_office' => 'كفر البطيخ', 'address' => 'م. كفر سعدبجوار المحطه', 'postal_area' => 'دمياط', ), 
	141 => array ( 'postal_code' => '34721', 'post_office' => 'شرباص', 'address' => 'الوحده المحليه- فارسكور/قريهشرباص', 'postal_area' => 'دمياط', ), 
	142 => array ( 'postal_code' => '34723', 'post_office' => 'السرو', 'address' => 'المساكن الشعبيه مركز الزرقا/السرو', 'postal_area' => 'دمياط', ), 
	143 => array ( 'postal_code' => '34724', 'post_office' => 'الزرقا', 'address' => 'المساكن الاقتصاديه مركز الزرقا ش المحطه', 'postal_area' => 'دمياط', ), 
	144 => array ( 'postal_code' => '35511', 'post_office' => 'المنصوره', 'address' => 'ش الجمهوريه / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	145 => array ( 'postal_code' => '35512', 'post_office' => 'ميت حدر', 'address' => 'مبني السكه الحديد ميت حدر / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	146 => array ( 'postal_code' => '35513', 'post_office' => 'رابع النجار', 'address' => 'سيدي عبد القادر / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	147 => array ( 'postal_code' => '35514', 'post_office' => 'الجلاء', 'address' => 'ش الجلاء / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	148 => array ( 'postal_code' => '35517', 'post_office' => 'البحر الصغير', 'address' => 'ش جوهر الصقلي / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	149 => array ( 'postal_code' => '35519', 'post_office' => 'كفر البدماص', 'address' => 'ش قناه السويس كفر البدماص / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	150 => array ( 'postal_code' => '35523', 'post_office' => 'جديله', 'address' => '13ش مساكن الرشاح جديله / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	151 => array ( 'postal_code' => '35631', 'post_office' => 'بلقاس', 'address' => 'بلقاس', 'postal_area' => 'شمال الدقهليه', ), 
	152 => array ( 'postal_code' => '35642', 'post_office' => 'المنزله', 'address' => 'مدينه المنزله', 'postal_area' => 'شمال الدقهليه', ), 
	153 => array ( 'postal_code' => '35661', 'post_office' => 'شربين', 'address' => 'ش السكه الحديد / شربين', 'postal_area' => 'شمال الدقهليه', ), 
	154 => array ( 'postal_code' => '35668', 'post_office' => 'بسنديله', 'address' => 'قريه بسنديله / بلقاس', 'postal_area' => 'شمال الدقهليه', ), 
	155 => array ( 'postal_code' => '35687', 'post_office' => 'نشا', 'address' => 'نشا / طلخا', 'postal_area' => 'شمال الدقهليه', ), 
	156 => array ( 'postal_code' => '35711', 'post_office' => 'اويش الحجر', 'address' => 'قريه اويش الحجر / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	157 => array ( 'postal_code' => '35718', 'post_office' => 'راس الخليج محطه', 'address' => 'راس الخليج / شربين', 'postal_area' => 'شمال الدقهليه', ), 
	158 => array ( 'postal_code' => '35719', 'post_office' => 'راس الخليج بلد', 'address' => 'راس الخليج / شربين', 'postal_area' => 'شمال الدقهليه', ), 
	159 => array ( 'postal_code' => '35725', 'post_office' => 'بداوي', 'address' => 'قريه بداوي / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	160 => array ( 'postal_code' => '35735', 'post_office' => 'تلبانه', 'address' => 'قريه تلبانه / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	161 => array ( 'postal_code' => '35737', 'post_office' => 'سلامون القماش', 'address' => 'قريه سلامون القماش / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	162 => array ( 'postal_code' => '35738', 'post_office' => 'شها', 'address' => 'قريه شها / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	163 => array ( 'postal_code' => '35744', 'post_office' => 'دكرنس', 'address' => 'دكرنس', 'postal_area' => 'شمال الدقهليه', ), 
	164 => array ( 'postal_code' => '35777', 'post_office' => 'ميت علي', 'address' => 'ميت علي / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	165 => array ( 'postal_code' => '35782', 'post_office' => 'طناح', 'address' => 'قريه طناح / المنصوره', 'postal_area' => 'شمال الدقهليه', ), 
	166 => array ( 'postal_code' => '35785', 'post_office' => 'بني عبيد', 'address' => 'بني عبيد', 'postal_area' => 'شمال الدقهليه', ), 
	167 => array ( 'postal_code' => '35789', 'post_office' => 'المطريه', 'address' => 'مدينه المطريه', 'postal_area' => 'شمال الدقهليه', ), 
	168 => array ( 'postal_code' => '35791', 'post_office' => 'الجماليه', 'address' => 'الجماليه', 'postal_area' => 'شمال الدقهليه', ), 
	169 => array ( 'postal_code' => '35794', 'post_office' => 'بطره', 'address' => 'قريه بطره / طلخا', 'postal_area' => 'شمال الدقهليه', ), 
	170 => array ( 'postal_code' => '41511', 'post_office' => 'الاسماعيليه', 'address' => 'ش الحريه / ميدان عرابي / الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	171 => array ( 'postal_code' => '41512', 'post_office' => 'الاسماعيليه / فرعي', 'address' => 'ش الجيش / سوق الجمله / الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	172 => array ( 'postal_code' => '41515', 'post_office' => 'القناه', 'address' => 'مبني الارشاد/هيئه القناه/الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	173 => array ( 'postal_code' => '41517', 'post_office' => 'عرايشه مصر', 'address' => 'ش المنوفيه/عرايشه مصر/قسم ثان الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	174 => array ( 'postal_code' => '41518', 'post_office' => 'عرايشه مصر ثان', 'address' => 'ش المنصوره والبحري/قسم ثان الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	175 => array ( 'postal_code' => '41521', 'post_office' => 'ابو عطوه', 'address' => 'ابوعطوه/ بجوارالمطافيء / الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	176 => array ( 'postal_code' => '41522', 'post_office' => 'جامعه قناه السويس', 'address' => 'مبني الجامعه القديم / الاسماعيليه / جامعه قناه السويس', 'postal_area' => 'الاسماعيليه', ), 
	177 => array ( 'postal_code' => '41523', 'post_office' => 'حي السلام / اسماعيليه', 'address' => 'ش المستشفي/ حي السلام / الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	178 => array ( 'postal_code' => '41526', 'post_office' => 'مديريه امن الاسماعيليه', 'address' => 'داخل مبني مديريه امن الاسماعيليه/ الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	179 => array ( 'postal_code' => '41527', 'post_office' => 'المنطقه الصناعيه', 'address' => 'المنطقه الصناعيه/لجنه الخدمات/مركز الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	180 => array ( 'postal_code' => '41528', 'post_office' => 'التمليك بالشيخ زويد', 'address' => 'ش التمليك/ بجوار المنتزه / الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	181 => array ( 'postal_code' => '41529', 'post_office' => 'التمليك التعاوني', 'address' => 'المرحله الخامسه/عماره 33 / الاسماعيليه / التمليك التعاوني', 'postal_area' => 'الاسماعيليه', ), 
	182 => array ( 'postal_code' => '41611', 'post_office' => 'القنطره غرب', 'address' => 'مركزالقنطره غرب/المساكن الاقتصاديه', 'postal_area' => 'الاسماعيليه', ), 
	183 => array ( 'postal_code' => '41614', 'post_office' => 'الضبعيه', 'address' => 'الضبعيه / سرابيوم / عماره رقم2 /الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	184 => array ( 'postal_code' => '41615', 'post_office' => 'عين غصين', 'address' => 'عين غصين / سرابيوم/ الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	185 => array ( 'postal_code' => '41616', 'post_office' => 'سرابيوم', 'address' => 'القريه النموذجيه/سرابيوم/ مركز فايد', 'postal_area' => 'الاسماعيليه', ), 
	186 => array ( 'postal_code' => '41617', 'post_office' => 'ابو سلطان', 'address' => 'ابو سلطان/سرابيوم/شارع الرئيسي / مركز فايد', 'postal_area' => 'الاسماعيليه', ), 
	187 => array ( 'postal_code' => '41618', 'post_office' => 'فايد', 'address' => 'فايد / ش مجلس المدينه', 'postal_area' => 'الاسماعيليه', ), 
	188 => array ( 'postal_code' => '41619', 'post_office' => 'قمه فايد', 'address' => 'قمه فايد/ داخل المحطه / فايد', 'postal_area' => 'الاسماعيليه', ), 
	189 => array ( 'postal_code' => '41621', 'post_office' => 'فناره', 'address' => 'فناره / ش الشهيد فريد ندي / فايد', 'postal_area' => 'الاسماعيليه', ), 
	190 => array ( 'postal_code' => '41622', 'post_office' => 'ابو صوير', 'address' => 'ابو صوير', 'postal_area' => 'الاسماعيليه', ), 
	191 => array ( 'postal_code' => '41623', 'post_office' => 'المحسمه', 'address' => 'المحسمه / ابوصوير/ الاسماعيليه', 'postal_area' => 'الاسماعيليه', ), 
	192 => array ( 'postal_code' => '41624', 'post_office' => 'القصاصين', 'address' => 'القصاصين/المساكن الاقتصاديه/عماره 7/التل الكبير', 'postal_area' => 'الاسماعيليه', ), 
	193 => array ( 'postal_code' => '41626', 'post_office' => 'التل الكبير', 'address' => 'التل الكبير / ش احمد عرابي', 'postal_area' => 'الاسماعيليه', ), 
	194 => array ( 'postal_code' => '41628', 'post_office' => 'معسكر عزت شرف', 'address' => 'داخل المعسكر / التل الكبير / معسكر عزت شرف', 'postal_area' => 'الاسماعيليه', ), 
	195 => array ( 'postal_code' => '42511', 'post_office' => 'بور سعيد', 'address' => 'ش الجيش / بورسعيد ومحمد محمود', 'postal_area' => 'بور سعيد', ), 
	196 => array ( 'postal_code' => '42512', 'post_office' => 'بور سعيد ثان', 'address' => 'ش عبادي والاتحاد / بورسعيد', 'postal_area' => 'بور سعيد', ), 
	197 => array ( 'postal_code' => '42513', 'post_office' => 'بور سعيد ثالث', 'address' => 'حي الزهور مبني التكامل الاجتماعي / بورسعيد', 'postal_area' => 'بور سعيد', ), 
	198 => array ( 'postal_code' => '42514', 'post_office' => 'ابو الحسن', 'address' => 'ش البلديه وشهداء القناه/ قسم العرب / ابو الحسن', 'postal_area' => 'بور سعيد', ), 
	199 => array ( 'postal_code' => '42515', 'post_office' => 'الامين والروس', 'address' => 'ش/ الامين وروس والانصار', 'postal_area' => 'بور سعيد', ), 
	200 => array ( 'postal_code' => '42516', 'post_office' => '6 اكتوبر', 'address' => 'المنطقه الثامنه', 'postal_area' => 'بور سعيد', ), 
	201 => array ( 'postal_code' => '42517', 'post_office' => 'سوق الجمله', 'address' => 'مبني الغرفه التجاريه / ش محمد علي', 'postal_area' => 'بور سعيد', ), 
	202 => array ( 'postal_code' => '42518', 'post_office' => 'القابوطي', 'address' => 'بولك 7 بالقابوطي', 'postal_area' => 'بور سعيد', ), 
	203 => array ( 'postal_code' => '42519', 'post_office' => 'حي الكويت', 'address' => 'عماره 32 / حي الكويت', 'postal_area' => 'بور سعيد', ), 
	204 => array ( 'postal_code' => '42521', 'post_office' => 'محافظه بور سعيد', 'address' => 'مبني المحافظه/ بور سعيد', 'postal_area' => 'بور سعيد', ), 
	205 => array ( 'postal_code' => '42523', 'post_office' => 'بور فؤاد', 'address' => '8 شارع 23 يوليو / بور فؤاد', 'postal_area' => 'بور سعيد', ), 
	206 => array ( 'postal_code' => '42524', 'post_office' => 'جامعه قناه السويس', 'address' => 'مساكن الهيئه /بورفؤاد / جامعه قناه السويس', 'postal_area' => 'بور سعيد', ), 
	207 => array ( 'postal_code' => '42525', 'post_office' => 'حي السلام', 'address' => 'مبني التنميه الحضاريه/حي السلام/قسم الضواحي', 'postal_area' => 'بور سعيد', ), 
	208 => array ( 'postal_code' => '42611', 'post_office' => 'الكاب', 'address' => 'المبني الاداري / قريه الكاب/ثان جنوب', 'postal_area' => 'بور سعيد', ), 
	209 => array ( 'postal_code' => '43511', 'post_office' => 'السويس', 'address' => 'شارع هدي شعراوي/ السويس', 'postal_area' => 'السويس', ), 
	210 => array ( 'postal_code' => '43512', 'post_office' => 'السويس فرعي', 'address' => 'مساكن الغريب عماره 145/ شقه 2', 'postal_area' => 'السويس', ), 
	211 => array ( 'postal_code' => '43513', 'post_office' => 'السويس ثان', 'address' => 'شارع طلعت حرب / السويس', 'postal_area' => 'السويس', ), 
	212 => array ( 'postal_code' => '43514', 'post_office' => 'الاربعين', 'address' => 'مساكن منتزه سعد/السويس/قسم الاربعين', 'postal_area' => 'السويس', ), 
	213 => array ( 'postal_code' => '43515', 'post_office' => 'الاربعين ثالث', 'address' => 'ش الجيش مساكن المثلث/السويس/قسم الاربعين', 'postal_area' => 'السويس', ), 
	214 => array ( 'postal_code' => '43517', 'post_office' => 'معسكر السويس', 'address' => 'المحطه العسكريه بفيصل / معسكر السويس', 'postal_area' => 'السويس', ), 
	215 => array ( 'postal_code' => '43519', 'post_office' => 'مدينه الصباح', 'address' => 'حي الجمهوريه / مدينه الصباح/ قسم فيصل', 'postal_area' => 'السويس', ), 
	216 => array ( 'postal_code' => '43522', 'post_office' => 'بورتوفيق/قسم السويس', 'address' => 'شارع القنال / بور توفيق', 'postal_area' => 'السويس', ), 
	217 => array ( 'postal_code' => '43713', 'post_office' => 'عتاقه', 'address' => 'مساكن السماد / عتاقه', 'postal_area' => 'السويس', ), 
	218 => array ( 'postal_code' => '43714', 'post_office' => 'الجبلايات', 'address' => 'جبلايه ابو عثمان / قسم الجناين', 'postal_area' => 'السويس', ), 
	219 => array ( 'postal_code' => '44511', 'post_office' => 'الزقازيق', 'address' => 'ش الجلاء / الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	220 => array ( 'postal_code' => '44512', 'post_office' => 'الزقازيق فرعي', 'address' => 'ش مدرسه الامريكان / الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	221 => array ( 'postal_code' => '44513', 'post_office' => 'الزقازيق محطه', 'address' => 'مبنه محطه السكه الحديد / الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	222 => array ( 'postal_code' => '44514', 'post_office' => 'قسم النحال', 'address' => 'ش النقراشي النحال / الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	223 => array ( 'postal_code' => '44516', 'post_office' => 'مجمع المصالح', 'address' => 'ش المحافظه / الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	224 => array ( 'postal_code' => '44648', 'post_office' => 'الروضه فاقوس', 'address' => 'الروضه / فاقوس', 'postal_area' => 'شمال الشرقيه', ), 
	225 => array ( 'postal_code' => '44654', 'post_office' => 'الحسينيه', 'address' => 'الحسينيه/ش المركز', 'postal_area' => 'شمال الشرقيه', ), 
	226 => array ( 'postal_code' => '44671', 'post_office' => 'ابو كبير', 'address' => 'ابو كبير / شارع التحرير', 'postal_area' => 'شمال الشرقيه', ), 
	227 => array ( 'postal_code' => '44711', 'post_office' => 'بردين', 'address' => 'قريه بردين / الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	228 => array ( 'postal_code' => '44718', 'post_office' => 'العصلوجي', 'address' => 'قريه العصلوجي/ الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	229 => array ( 'postal_code' => '44719', 'post_office' => 'ابو الشقوق', 'address' => 'ابو الشقوق/ش الجلاء/ مركزكفرصقر', 'postal_area' => 'شمال الشرقيه', ), 
	230 => array ( 'postal_code' => '44722', 'post_office' => 'ابو الاخضر', 'address' => 'ابو الاخضر / الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	231 => array ( 'postal_code' => '44735', 'post_office' => 'الصالحيه', 'address' => 'الصالحيه / فاقوس', 'postal_area' => 'شمال الشرقيه', ), 
	232 => array ( 'postal_code' => '44743', 'post_office' => 'الا براهيميه', 'address' => 'الابراهيميه / امام مضرب الارز', 'postal_area' => 'شمال الشرقيه', ), 
	233 => array ( 'postal_code' => '44758', 'post_office' => 'الزنكلون', 'address' => 'قريه الزنكلون / الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	234 => array ( 'postal_code' => '44759', 'post_office' => 'شيبه النكاريه', 'address' => 'ش الوحده شيبه النكاريه / الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	235 => array ( 'postal_code' => '44783', 'post_office' => 'بني عامر', 'address' => 'بني عامر/ الزقازيق', 'postal_area' => 'جنوب الشرقيه', ), 
	236 => array ( 'postal_code' => '44856', 'post_office' => 'جنوب سهل الحسينيه', 'address' => 'جنوب سهل الحسينيه / الزقازيق', 'postal_area' => 'شمال الشرقيه', ), 
	237 => array ( 'postal_code' => '44889', 'post_office' => 'البرنس', 'address' => 'قريه البرنس / مركز الزقازيق', 'postal_area' => 'شمال الشرقيه', ), 
);